version: '3.8'

services:
  kong:
    image: kong:latest
    ports:
      - "8000:8000"   # Proxy HTTP
      - "8443:8443"   # Proxy HTTPS
      - "4001:4001"   # Admin API
      - "4444:4444"   # Admin API HTTPS
      - "4002:4002"   # Admin GUI (Kong Manager)
    volumes:
      - ./kong.yml:/usr/local/kong/declarative/kong.yml:ro
    environment:
      KONG_DATABASE: off
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:4001
      KONG_ADMIN_GUI_LISTEN: 0.0.0.0:4002
      KONG_ADMIN_GUI_URL: http://localhost:4002