version: '3.8'

services:
  kong-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-kong}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-kong}
      MYSQL_USER: ${MYSQL_USER:-kong}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-kong}
    ports:
      - "3307:3306"
    volumes:
      - kong-db-data:/var/lib/mysql

  kong-migrations:
    image: kong:latest
    depends_on:
      - kong-db
    entrypoint: ["/bin/sh", "-c"]
    command: ["kong migrations bootstrap && kong migrations up"]
    environment:
      KONG_DATABASE: mysql
      KONG_PG_HOST: kong-db
      KONG_PG_PORT: 3307
      KONG_PG_USER: ${MYSQL_USER:-kong}
      KONG_PG_PASSWORD: ${MYSQL_PASSWORD:-kong}
      KONG_PG_DATABASE: ${MYSQL_DATABASE:-kong}

  kong:
    image: kong:latest
    depends_on:
      - kong-db
    ports:
      - "8000:8000"   # Proxy HTTP
      - "8443:8443"   # Proxy HTTPS
      - "4001:4001"   # Admin API
      - "4444:4444"   # Admin API HTTPS
      - "4002:4002"   # Admin GUI (Kong Manager)
    environment:
      KONG_DATABASE: mysql
      KONG_PG_HOST: kong-db
      KONG_PG_PORT: 3307
      KONG_PG_USER: ${MYSQL_USER:-kong}
      KONG_PG_PASSWORD: ${MYSQL_PASSWORD:-kong}
      KONG_PG_DATABASE: ${MYSQL_DATABASE:-kong}
      KONG_ADMIN_LISTEN: 0.0.0.0:4001
      KONG_ADMIN_GUI_LISTEN: 0.0.0.0:4002
      KONG_ADMIN_GUI_URL: http://localhost:4002
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr

volumes:
  kong-db-data:
